version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:13-buster
    steps:
      - checkout
      - run:
          name: Install deps for deasync
          command: apt-get update; apt-get install -y python3.6 make build-essential
      - run:
          name: Install project dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run unit tests
          command: yarn test --coverage
      - store_artifacts:
          path: junit
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: junit
